
[[item_type]]
id = "TestItem"
name = "Dynamic Item Type"
description = "This item type is used for testing, if the dynamic item type files work"
icon = "FILE MOD Icons/SDF.png"

actor_path = "/Game/Mods/DemoMod/BP_TestItemActor.BP_TestItemActor_C"
