
[[recipe]]
id = "CustomRecipe"
name = "Custom Recipe"
description = "This is a custom and data driven recipe"

available_in_lifepod = true # Optional; only when set to true will this actually do something
category = "CustomCategory"
icon = "ITEM CookedBluemoon" # This will use the thumbnail from the given item
crafting_time = 5.0 # Floating point crafting time in seconds

[[recipe.ingredients]]
Titanium = 2

[[recipe.outputs]]
CookedBluemoon = 6

[[recipe.unlocking_rule]]
set_id = "PickupRuleSet"
pickup_items = [
    "Titanium"
]

[[recipe.unlocking_rule]]
set_id = "ScanDataSet"
scan_data = [
    "Titanium"
]


[[recipe]]
id = "CustomProcessorRecipe"
name = "Custom Processor Recipe"
description = "This is a custom recipe that can be crafted using a Processor"

category = "ProcessorBiofuel" # Where something is crafted is entirely decided by the category
icon = "DEFAULT" # Optional, default is the "Alterra Cicada" logo, used in the game as a placeholder
crafting_time = 15.0

[[recipe.ingredients]]
CookedBluemoon = 3
CookedHalfmoon = 3

[[recipe.outputs]]
BiofuelBlock = 3
