
[[recipe_delete]]
id = "Flashlight"


[[recipe_modify]]
id = "MetalSalvage"
description = "This is a modified description :)"
available_in_lifepod = false # You can override the lifepod state

[[recipe_modify.ingredients]]
MetalSalvage = 2
Copper = 2

[[recipe_modify.outputs]]
Titanium = 6


[[recipe_modify]]
id = "BuilderTool"
remove_unlocking_rules = true # This will remove all unlocking requirements. Not necessary when overwriting.


[[recipe]]
id = "CustomRecipe"
name = "Custom Recipe"
description = "This is a custom and data driven recipe"

available_in_lifepod = true # Optional; only when set to true will this actually do something
category = "CustomCategory"
icon = "ITEM CookedBluemoon" # This will use the thumbnail from the given item; optional, default is the "Alterra Cicada" logo, used in the game as a placeholder
crafting_time = 5.0 # Floating point crafting time in seconds

[[recipe.ingredients]]
Titanium = 2

[[recipe.outputs]]
CookedBluemoon = 6

[[recipe.unlocking_rule]]
set_id = "PickupRuleSet"
pickup_items = [
    "Titanium"
]

[[recipe.unlocking_rule]]
set_id = "ScanDataSet"
scan_data = [
    "Titanium"
]


[[recipe]]
id = "CustomProcessorRecipe"
name = "Custom Processor Recipe"
description = "This is a custom recipe that can be crafted using a Processor"

category = "ProcessorBiofuel" # Where something is crafted is entirely decided by the category
crafting_time = 15.0

[[recipe.ingredients]]
CookedBluemoon = 3
CookedHalfmoon = 3

[[recipe.outputs]]
BiofuelBlock = 3


[[recipe]]
id = "CustomBuilderRecipe"
name = "Custom Builder Recipe"
description = "This is a recipe for testing custom builder actions"

category = "CustomBuilderActions"

[[recipe.ingredients]]
Titanium = 3
Copper = 1

[[recipe.outputs]]
TableDining = 1


[[recipe]]
id = "ItemTestRecipe"
name = "Item Test Recipe"
description = "Nope"

category = "CustomCategory"

[[recipe.ingredients]]
Titanium = 1

[[recipe.outputs]]
CustomItem = 1
