
[[category]]
id = "CustomCategory"
name = "Custom Food"
description = "Custom and data driven food category"

crafted_by = "Fabricator"
parent_category = "Sustenance" # Optional; a parent category is currently necessary for everything but Processor categories
icon = "ITEM Titanium" # Optional; placeholder Alterra Cicada icon => not sure where this icon is actually used


[[category]]
id = "CustomBuilderActions"
name = "Custom Builder Actions"
description = "This category is for testing custom builder actions"

crafted_by = "BuilderTool"
parent_category = "BuilderBaseObjectCategory"


[[category]]
id = "CustomRootCategory"
name = "Custom Root Category"
description = "This category lives in a fabricators root"
show_when_empty = true

crafted_by = "Fabricator"


[[category_modify]]
id = "Sustenance"
name = "Cooked stuff or sum"
ordering_index = -999


[[category_delete]]
id = "Consumables"
